### ISSUE TITLE
Bedre commit-meldinger

### ISSUE THREAD

**Issue by asmadsen** [Westerdals/pgr203-assignment-1-TobiasLab#2]
For å få arbeidskravet godkjent skal du ha mer enn 1 meningsfull commit med en beskrivende commit-melding for å vise at dere behersker git som er progammeringsverktøy.

**Comment by TobiasLab** [comment]
Bare for å kommentere på akkurat dette. Det var en del misforståelser rundt hva som faktisk skulle bli lastet opp på github her. Vi startet av med å laste opp koden for videoen vi lagde, men det viste seg at det ikke var den vi skulle laste opp her. Der hadde vi mange flere commits med ordentlige commit-meldinger. Det som er her nå er bare én stor commit jeg måtte gjøre i siste liten for å få levert.

**Comment by jhannes** [comment]
Nå er commitmeldingene korrigert og innleveringen vil derfor godkjennes
